trigger:
  branches:
    include: [ main ]

# Global variable: one secret name used everywhere
variables:
  secretName: APP_CLIENT_SECRET

stages:
  - template: templates/stage-fetch-one-kv-secret.yml
    parameters:
      stageName: DEV
      environmentName: dev
      serviceConnection: sc-azure-dev
      keyVaultName: kv-yourapp-dev
      secretName: $(secretName)

  - template: templates/stage-fetch-one-kv-secret.yml
    parameters:
      stageName: QA
      environmentName: qa
      serviceConnection: sc-azure-qa
      keyVaultName: kv-yourapp-qa
      secretName: $(secretName)

  - template: templates/stage-fetch-one-kv-secret.yml
    parameters:
      stageName: STAGE
      environmentName: stage
      serviceConnection: sc-azure-stage
      keyVaultName: kv-yourapp-stage
      secretName: $(secretName)

  - template: templates/stage-fetch-one-kv-secret.yml
    parameters:
      stageName: PROD
      environmentName: prod
      serviceConnection: sc-azure-prod
      keyVaultName: kv-yourapp-prod
      secretName: $(secretName)

